### ISSUE TITLE
Visual issue on the site

### ISSUE THREAD

**Issue by nalexn** [Juanpe/About-SwiftUI#108]
<img width="860" alt="Screenshot 2020-01-24 at 16 56 46" src="https://user-images.githubusercontent.com/1594746/73064152-bfc69580-3eca-11ea-9227-7ddd49c7621b.png">

https://juanpe.github.io/About-SwiftUI/

Apparently, the Jekyll markdown interpreter doesn't like the Chinese characters.

**Comment by Juanpe** [comment]
Hi @nalexn, thanks for reporting, I’m going to check it. It seems that the parser has problems

**Comment by Juanpe** [comment]
Solved :)
