### ISSUE TITLE
The README file in this repo has some bad links

### ISSUE THREAD

**Issue by MrCull** [Juanpe/About-SwiftUI#132]
The README file in this repo has some bad links

Status code [404:NotFound] - Link: https://developer.apple.com/documentation/ios-ipados-release-notes/ios-ipados-14-beta-release-notes
Status code [404:NotFound] - Link: https://www.udemy.com/user/anoop-tomar/
Status code [404:NotFound] - Link: https://github.com/Juanpe/About-SwiftUI/blob/master/linkedin.com/in/stephen-destefano-973583193
Status code [404:NotFound] - Link: https://johnoreilly.dev/2019/06/08/swiftui-meetings-kotlin-multiplatform.html
Status code [404:NotFound] - Link: https://github.com/swifterH/Lists_-_Navigation_SwiftUI
Status code [404:NotFound] - Link: https://github.com/SwiftUIExtensions/Sliders

This was found by an new experimental hobby project that I have just created: https://github.com/MrCull/GitHub-Repo-ReadMe-Dead-Link-Finder
If this has been in any way helpful then please consider giving the above Repo a Star.

**Comment by solankidivyam** [comment]
Hey there Mr Cull, can I fix this issue. This would be my first contribution. I thought I would start with something naive. If possible i will try to replace them or otherwise will change the link to something relevant.

**Comment by MrCull** [comment]
Hey, well that's probably not a question for me.
@Juanpe owns this repo so perhaps can provide further info to you regarding if you can fix, and what to do if any bad link does note have an obvious solution.

For-up-to date list of broken links see:
https://githubreadmechecker.com/Home/Search?SingleRepoUri=https%3A%2F%2Fgithub.com%2Fjuanpe%2FAbout-SwiftUI&User=&NumberOfReposToSearchFor=&MinStar=&UpdatedAfter=&SearchSort=2&SortAscDsc=1

**Comment by Juanpe** [comment]
Hi @solankidivyam, your PR will be very welcomed :)

**Comment by solankidivyam** [comment]
@Juanpe, PR is submitted..
